---
title: "Activity 3 - MLR"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load_packages}

library(tidyverse)
library(tidymodels)

```


```{r load_library2}

library(GGally)

```

```{r load_data}

music_50s <- read.csv("1950[1].csv")
music_60s <- read.csv("1960[1].csv")
music_70s <- read.csv("1970[1].csv")
music_80s <- read.csv("1980[1].csv")
music_90s <- read.csv("1990[1].csv")
music_00s <- read.csv("2000[1].csv")
music_10s <- read.csv("2010[1].csv")

```

```{r combine_data}

music <- rbind(music_50s, music_60s, music_70s, music_80s, music_90s, music_00s,
               music_10s)
```

```{r exploring_bpm_nrgy}
  music %>% 
    select(pop, bpm, nrgy) %>% 
    ggpairs()
    ```

```{r exploring_bpm_dnce}
  music %>% 
    select(pop, bpm, dnce) %>% 
    ggpairs()
    ```
    
```{r exploring_bpm_dB}
  music %>% 
    select(pop, bpm, dB) %>% 
    ggpairs()
    ```
  
```{r exploring_bpm_live}
  music %>% 
    select(pop, bpm, live) %>% 
    ggpairs()
```
    
```{r exploring_bpm_val}
  music %>% 
    select(pop, bpm, val) %>% 
    ggpairs()
```    

```{r exploring_bpm_dur}
  music %>% 
    select(pop, bpm, dur) %>% 
    ggpairs()
```

```{r exploring_bpm_acous}
  music %>% 
    select(pop, bpm, acous) %>% 
    ggpairs()
```

```{r exploring_bpm_spch}
  music %>% 
    select(pop, spch) %>% 
    ggpairs()
    ```
    
```{r exploring_nrgy_dnce}
  music %>% 
    select(pop, nrgy, dnce) %>% 
    ggpairs()
    ```

```{r exploring_nrgy_dB}
  music %>% 
    select(pop, nrgy, dB) %>% 
    ggpairs()
    ```

```{r exploring_variable_nrgy_live}
  music %>% 
    select(pop, nrgy, live) %>% 
    ggpairs()
    ```

```{r exploring_variable_nrgy_val}
  music %>% 
    select(pop, nrgy, val) %>% 
    ggpairs()
    ```

```{r exploring_variable_nrgy_dur}
  music %>% 
    select(pop, nrgy, dur) %>% 
    ggpairs()
    ```

```{r exploring_variable_nrgy_acous}
  music %>% 
    select(pop, nrgy, acous) %>% 
    ggpairs()
    ```
    
```{r exploring_variable_nrgy_spch}
  music %>% 
    select(pop, nrgy, spch) %>% 
    ggpairs()
    ```
    
```{r exploring_variable_dnce_dB}
  music %>% 
    select(pop, dnce, dB) %>% 
    ggpairs()
    ```

```{r exploring_variable_dnce_live}
  music %>% 
    select(pop, dnce, live) %>% 
    ggpairs()
    ```

```{r exploring_variable_dnce_val}
  music %>% 
    select(pop, dnce, val) %>% 
    ggpairs()
    ```

```{r exploring_variable_dnce_dur}
  music %>% 
    select(pop, dnce, dur) %>% 
    ggpairs()
    ```
    
```{r exploring_variable_dnce_acous}
  music %>% 
    select(pop, dnce, acous) %>% 
    ggpairs()
    ```
    
```{r exploring_variable_dnce_spch}
  music %>% 
    select(pop, dnce, spch) %>% 
    ggpairs()
    ```

```{r exploring_variable_dB_live}
  music %>% 
    select(pop, dB, live) %>% 
    ggpairs()
    ```

```{r exploring_variable_dB_val}
  music %>% 
    select(pop, dB, val) %>% 
    ggpairs()
    ```

```{r exploring_variable_dB_dur}
  music %>% 
    select(pop, dB, dur) %>% 
    ggpairs()
    ```

```{r exploring_variable_dB_acous}
  music %>% 
    select(pop, dB, acous) %>% 
    ggpairs()
    ```

```{r exploring_variable_dB_spch}
  music %>% 
    select(pop, dB, spch) %>% 
    ggpairs()
    ```

```{r exploring_variable_live_val}
  music %>% 
    select(pop, live, val ) %>% 
    ggpairs()
```

```{r exploring_variable_live_dur}
  music %>% 
    select(pop, live, dur) %>% 
    ggpairs()
```

```{r exploring_variable_live_acous}
  music %>% 
    select(pop, live, acous) %>% 
    ggpairs()
```


```{r exploring_variable_live_spch}
  music %>% 
    select(pop, live, spch) %>% 
    ggpairs()
```

```{r exploring_variable_val_dur}
  music %>% 
    select(pop, val, dur) %>% 
    ggpairs()
```

```{r exploring_variable_val_acous}
  music %>% 
    select(pop, val, acous) %>% 
    ggpairs()
```

```{r exploring_variable_val_spch}
  music %>% 
    select(pop, val, spch) %>% 
    ggpairs()
```

```{r exploring_variable_dur_acous}
  music %>% 
    select(pop, dur, acous) %>% 
    ggpairs()
```

```{r exploring_variable_dur_spch}
  music %>% 
    select(pop, dur, spch) %>% 
    ggpairs()
```

```{r exploring_variable_acous_spch}
  music %>% 
    select(pop, acous, spch) %>% 
    ggpairs()
```

``` {r linear_regression}
  lm_spec <- linear_reg() %>%
  set_mode("regression") %>%
  set_engine("lm")

  lm_spec

  mlr_mod <- lm_spec %>% 
  fit(pop ~ bpm + nrgy + dnce + dB + live + val + dur + acous +spch,
      data = music)

  tidy(mlr_mod)
```

$$
\hat{y} = 68.144 +  0.020 \times bpm - 0.095 \times nrgy + 0.142 \times dnce + 0.965 \times dB - 0.029 \times live - 0.113 \times val + 0.40 \times dur - 0.165 \times acous + 0.176 \times spch
$$